Ayeeta/player movement
agdabs/BevviesRun pull request #2
Opened 2019-08-10 00:58 UTC by anitatse

2019-08-10 22:23 UTC, mikeslgoh commented
![](https://github.trello.services/images/mini-trello-icon.png) [Player Movement](https://trello.com/c/Sf1ZH5ic/10-player-movement)

2019-08-12 23:28 UTC, mikeslgoh requested changes
Just some minor things and after that, it's good to go :)

2019-08-12 23:28 UTC, mikeslgoh commented on Assets/Scenes/SampleScene.unity
> +  m_AmbientSkyColor: {r: 1, g: 1, b: 1, a: 1}
I'm not actually reading the code from this but please create a new scene with these changes rather than working directly on SampleScene. Just because this might cause conflicts with others.

2019-08-12 23:28 UTC, mikeslgoh commented on Assets/Scripts/PlayerController.cs
> +    private float jumpForce = 35;
could we set this to public so that we can play around with this field as well?

2019-08-14 16:31 UTC, mikeslgoh approved these changes
Looks good to me :)

2019-08-14 16:53 UTC, jagr approved these changes
Very beautiful circle and square, bounces around as intended, doesn't go out of the box and can provide many hours of fun! Nice!

2019-08-14 16:55 UTC, merged